// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVIx_oiqLONGNIO0t5ISqrGKLdq1fQmfA',
    appId: '1:134776301802:web:df8ce77091c0db3a594f93',
    messagingSenderId: '134776301802',
    projectId: 'teaser-app-2a731',
    authDomain: 'teaser-app-2a731.firebaseapp.com',
    storageBucket: 'teaser-app-2a731.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5i_9ay-_pvWINOdmurLQEgLnuufCz2tA',
    appId: '1:134776301802:android:d29dc53697940bde594f93',
    messagingSenderId: '134776301802',
    projectId: 'teaser-app-2a731',
    storageBucket: 'teaser-app-2a731.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPMTRrEyHDxV4fPm9MbuTxu5qClSKH2ME',
    appId: '1:134776301802:ios:879c7662a990ce9b594f93',
    messagingSenderId: '134776301802',
    projectId: 'teaser-app-2a731',
    storageBucket: 'teaser-app-2a731.appspot.com',
    iosBundleId: 'com.example.teaser',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPMTRrEyHDxV4fPm9MbuTxu5qClSKH2ME',
    appId: '1:134776301802:ios:2255e158e29d7d87594f93',
    messagingSenderId: '134776301802',
    projectId: 'teaser-app-2a731',
    storageBucket: 'teaser-app-2a731.appspot.com',
    iosBundleId: 'com.example.teaser.RunnerTests',
  );
}
